---
- name: Make Pakiti configuration available in Apache
  template:
    src: "{{ pakiti_webserver_conf_template }}"
    dest: /etc/apache2/conf-available/pakiti.conf
    owner: root
    mode: 0644

- name: Activate Pakiti in Apache
  command: "a2enconf pakiti"
