- name: Make sure PHP is available
  package:
    name: [ 'php', 'php-cli', 'php-curl', 'php-dom', 'git' ]

# there must be a better way to support different distros ...
 name: Install MySQL support for PHP at CentOS
  package:
    name: [ 'php-mysqli' ]
    state: present
  when: ansible_facts['distribution'] == 'CentOS'

- name: Install MySQL support for PHP at Debian
  package:
    name: [ 'php-mysql' ]
    state: present
  when: ansible_facts['distribution'] == 'Debian'

- name: Download repository from github and place it to /var/www
  shell: git clone https://github.com/CESNET/pakiti-server /var/www/pakiti-server
  args:
    executable: /bin/bash

- name: Create /etc/pakiti directory
  file:
    dest: /etc/pakiti
    state: directory
    owner: root
    mode: 0755

- name: Populate Pakiti configuration
  template:
    src: etc/pakiti/Config.php.j2
    dest: /etc/pakiti/Config.php
    owner: root
    mode: 0644

- name: Initalize Pakiti database and create the application user
  shell: "php /var/www/pakiti-server/install/initDB.php --reInitialize --user-name={{ mysql_root_name }} --password={{ mysql_root_password }}"
  args:
    chdir: '/var/www/pakiti-server/install'

- name: Enable Pakiti in Apache
  include_tasks: debian-apache-conf.yaml
  when: ansible_facts['distribution'] == 'Debian'
- name: Enable Pakiti in Apache
  include_tasks: rh-apache-conf.yaml
  when: ansible_facts['distribution'] == 'CentOS'


