---
- name: Enable Pakiti in Apache
  template:
    src: "{{ pakiti_webserver_conf_template }}"
    dest: /etc/httpd/conf.d/pakiti.conf

- name: Restart Apache to load new configuration
  service:
    name: httpd
    state: reloaded
